git:
  depth: 1
language: node_js
node_js:
  - '10'
cache:
  yarn: true
install:
  - yarn global add hexo
  - yarn install
script:
  - hexo generate
# https://docs.travis-ci.com/user/deployment/pages/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: false
  on:
    branch: develop
  local_dir: public
  target_branch: master
